[package]
name = "daughter_pcb_comm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecu_diagnostics="0.90.52"
serial-rs = {git="https://github.com/rnd-ash/serial-rs"}
packed_struct="0.10.0"
dbus="0.9.6"
clap={version="4.0.32", features=["derive"]}
bitflags="1.3.2"
log="0.4.17"
env_logger="0.10.0"
tokio={ version = "1.23.0", features = ["full"] }
futures="0.3.25"
bluer={version="0.15.5", features=["bluetoothd"]}