
#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
/**
* AUTOGENERATED BY convert.py
* DO NOT EDIT THIS FILE!
*
* IF MODIFICATIONS NEED TO BE MADE, MODIFY can_data.txt!
*
* CAN Defintiion for ECU 'BSG'
*/
    
pub const BSG_A1_CAN_ID: u16 = 0x0009;
pub const SD_RS_BSG_CAN_ID: u16 = 0x07D2;

/// Heated rear window control
#[derive(Debug, Copy, Clone, PartialEq, Eq, Ord, PartialOrd)]
#[repr(C)]
pub enum BSG_A1_HHS_BSG {
	NORMAL = 0, // Normal operation
	HHS_AUS_BSG = 1, // Rear window off
	HHS_EIN_BSG = 2, // Rear window on
	SNV = 3, // Signal not available
}

impl TryFrom<u8> for BSG_A1_HHS_BSG {
	type Error = ();
	fn try_from(value: u8) -> Result<Self, Self::Error> {
		match value {
			0 => Ok(Self::NORMAL),
			1 => Ok(Self::HHS_AUS_BSG),
			2 => Ok(Self::HHS_EIN_BSG),
			3 => Ok(Self::SNV),
			_ => Err(())
		}
	}
}

pub struct BSG_A1(u64);

impl BSG_A1 {

	/// Gets CAN ID of BSG_A1
	pub fn get_canid() -> u16 { BSG_A1_CAN_ID }
    /// Sets Vehicle power supply emergency mode: Prio1 and Prio2 consumers off, second battery supports

    pub fn set_BN_NTLF(&mut self, value: bool){ self.0 = (self.0 & 0x7fffffffffffffff) | ((value as u64) & 0x1) << 63; }

    /// Gets Vehicle power supply emergency mode: Prio1 and Prio2 consumers off, second battery supports
    pub fn get_BN_NTLF(&self) -> bool { (self.0 >> 63 & 0x1) != 0 }
        
    /// Sets On-board power supply emergency: Prio1 consumers off

    pub fn set_BN_NTLF_P1(&mut self, value: bool){ self.0 = (self.0 & 0xbfffffffffffffff) | ((value as u64) & 0x1) << 62; }

    /// Gets On-board power supply emergency: Prio1 consumers off
    pub fn get_BN_NTLF_P1(&self) -> bool { (self.0 >> 62 & 0x1) != 0 }
        
    /// Sets On-board network emergency operation: Prio2 consumers off

    pub fn set_BN_NTLF_P2(&mut self, value: bool){ self.0 = (self.0 & 0xdfffffffffffffff) | ((value as u64) & 0x1) << 61; }

    /// Gets On-board network emergency operation: Prio2 consumers off
    pub fn get_BN_NTLF_P2(&self) -> bool { (self.0 >> 61 & 0x1) != 0 }
        
    /// Sets On-board network warning: Starter line. interrupt or backup starter battery. malfunction

    pub fn set_BN_WARN4(&mut self, value: bool){ self.0 = (self.0 & 0xf7ffffffffffffff) | ((value as u64) & 0x1) << 59; }

    /// Gets On-board network warning: Starter line. interrupt or backup starter battery. malfunction
    pub fn get_BN_WARN4(&self) -> bool { (self.0 >> 59 & 0x1) != 0 }
        
    /// Sets Vehicle electrical system warning: BSG/current sensor defective or relay K2 defective

    pub fn set_BN_WARN3(&mut self, value: bool){ self.0 = (self.0 & 0xfbffffffffffffff) | ((value as u64) & 0x1) << 58; }

    /// Gets Vehicle electrical system warning: BSG/current sensor defective or relay K2 defective
    pub fn get_BN_WARN3(&self) -> bool { (self.0 >> 58 & 0x1) != 0 }
        
    /// Sets On-board network warning: Emergency operation (Prio1 or Prio2 consumption off)

    pub fn set_BN_WARN2(&mut self, value: bool){ self.0 = (self.0 & 0xfdffffffffffffff) | ((value as u64) & 0x1) << 57; }

    /// Gets On-board network warning: Emergency operation (Prio1 or Prio2 consumption off)
    pub fn get_BN_WARN2(&self) -> bool { (self.0 >> 57 & 0x1) != 0 }
        
    /// Sets On-board network warning: emergency operation (priority 1 & 2 consumption off, second battery supported)

    pub fn set_BN_WARN1(&mut self, value: bool){ self.0 = (self.0 & 0xfeffffffffffffff) | ((value as u64) & 0x1) << 56; }

    /// Gets On-board network warning: emergency operation (priority 1 & 2 consumption off, second battery supported)
    pub fn get_BN_WARN1(&self) -> bool { (self.0 >> 56 & 0x1) != 0 }
        
    /// Sets Battery is not charging

    pub fn set_BN_KL61(&mut self, value: bool){ self.0 = (self.0 & 0xff7fffffffffffff) | ((value as u64) & 0x1) << 55; }

    /// Gets Battery is not charging
    pub fn get_BN_KL61(&self) -> bool { (self.0 >> 55 & 0x1) != 0 }
        
    /// Sets Battery old

    pub fn set_SOHS_B(&mut self, value: bool){ self.0 = (self.0 & 0xffefffffffffffff) | ((value as u64) & 0x1) << 52; }

    /// Gets Battery old
    pub fn get_SOHS_B(&self) -> bool { (self.0 >> 52 & 0x1) != 0 }
        
    /// Sets Battery partially discharged

    pub fn set_SOCS_B(&mut self, value: bool){ self.0 = (self.0 & 0xfffbffffffffffff) | ((value as u64) & 0x1) << 50; }

    /// Gets Battery partially discharged
    pub fn get_SOCS_B(&self) -> bool { (self.0 >> 50 & 0x1) != 0 }
        
    /// Sets Launch availability

    pub fn set_SOCS_START(&mut self, value: bool){ self.0 = (self.0 & 0xfffdffffffffffff) | ((value as u64) & 0x1) << 49; }

    /// Gets Launch availability
    pub fn get_SOCS_START(&self) -> bool { (self.0 >> 49 & 0x1) != 0 }
        
    /// Sets Heated rear window control

    pub fn set_HHS_BSG(&mut self, value: BSG_A1_HHS_BSG){ self.0 = (self.0 & 0xffff3fffffffffff) | ((value as u64) & 0x3) << 46; }

    /// Gets Heated rear window control
    pub fn get_HHS_BSG(&self) -> std::result::Result<BSG_A1_HHS_BSG, ()> { return BSG_A1_HHS_BSG::try_from((self.0 >> 46 & 0x3) as u8) }
        
    /// Sets Battery SG active

    pub fn set_BSG_AKT(&mut self, value: bool){ self.0 = (self.0 & 0xfffffeffffffffff) | ((value as u64) & 0x1) << 40; }

    /// Gets Battery SG active
    pub fn get_BSG_AKT(&self) -> bool { (self.0 >> 40 & 0x1) != 0 }
        
}
pub struct SD_RS_BSG(u64);

impl SD_RS_BSG {

	/// Gets CAN ID of SD_RS_BSG
	pub fn get_canid() -> u16 { SD_RS_BSG_CAN_ID }
    /// Sets Identification for > 8 bytes

    pub fn set_BSG_KENN(&mut self, value: bool){ self.0 = (self.0 & 0x7fffffffffffffff) | ((value as u64) & 0x1) << 63; }

    /// Gets Identification for > 8 bytes
    pub fn get_BSG_KENN(&self) -> bool { (self.0 >> 63 & 0x1) != 0 }
        
    /// Sets error vector 07h

    pub fn set_BSG_FV07(&mut self, value: bool){ self.0 = (self.0 & 0xbfffffffffffffff) | ((value as u64) & 0x1) << 62; }

    /// Gets error vector 07h
    pub fn get_BSG_FV07(&self) -> bool { (self.0 >> 62 & 0x1) != 0 }
        
    /// Sets error vector 06h

    pub fn set_BSG_FV06(&mut self, value: bool){ self.0 = (self.0 & 0xdfffffffffffffff) | ((value as u64) & 0x1) << 61; }

    /// Gets error vector 06h
    pub fn get_BSG_FV06(&self) -> bool { (self.0 >> 61 & 0x1) != 0 }
        
    /// Sets error vector 05h

    pub fn set_BSG_FV05(&mut self, value: bool){ self.0 = (self.0 & 0xefffffffffffffff) | ((value as u64) & 0x1) << 60; }

    /// Gets error vector 05h
    pub fn get_BSG_FV05(&self) -> bool { (self.0 >> 60 & 0x1) != 0 }
        
    /// Sets error vector 04h

    pub fn set_BSG_FV04(&mut self, value: bool){ self.0 = (self.0 & 0xf7ffffffffffffff) | ((value as u64) & 0x1) << 59; }

    /// Gets error vector 04h
    pub fn get_BSG_FV04(&self) -> bool { (self.0 >> 59 & 0x1) != 0 }
        
    /// Sets error vector 03h

    pub fn set_BSG_FV03(&mut self, value: bool){ self.0 = (self.0 & 0xfbffffffffffffff) | ((value as u64) & 0x1) << 58; }

    /// Gets error vector 03h
    pub fn get_BSG_FV03(&self) -> bool { (self.0 >> 58 & 0x1) != 0 }
        
    /// Sets error vector 02h

    pub fn set_BSG_FV02(&mut self, value: bool){ self.0 = (self.0 & 0xfdffffffffffffff) | ((value as u64) & 0x1) << 57; }

    /// Gets error vector 02h
    pub fn get_BSG_FV02(&self) -> bool { (self.0 >> 57 & 0x1) != 0 }
        
    /// Sets error vector 01h

    pub fn set_BSG_FV01(&mut self, value: bool){ self.0 = (self.0 & 0xfeffffffffffffff) | ((value as u64) & 0x1) << 56; }

    /// Gets error vector 01h
    pub fn get_BSG_FV01(&self) -> bool { (self.0 >> 56 & 0x1) != 0 }
        
    /// Sets error vector 0Fh

    pub fn set_BSG_FV0F(&mut self, value: bool){ self.0 = (self.0 & 0xff7fffffffffffff) | ((value as u64) & 0x1) << 55; }

    /// Gets error vector 0Fh
    pub fn get_BSG_FV0F(&self) -> bool { (self.0 >> 55 & 0x1) != 0 }
        
    /// Sets error vector 0Eh

    pub fn set_BSG_FV0E(&mut self, value: bool){ self.0 = (self.0 & 0xffbfffffffffffff) | ((value as u64) & 0x1) << 54; }

    /// Gets error vector 0Eh
    pub fn get_BSG_FV0E(&self) -> bool { (self.0 >> 54 & 0x1) != 0 }
        
    /// Sets error vector 0Dh

    pub fn set_BSG_FV0D(&mut self, value: bool){ self.0 = (self.0 & 0xffdfffffffffffff) | ((value as u64) & 0x1) << 53; }

    /// Gets error vector 0Dh
    pub fn get_BSG_FV0D(&self) -> bool { (self.0 >> 53 & 0x1) != 0 }
        
    /// Sets error vector 0Ch

    pub fn set_BSG_FV0C(&mut self, value: bool){ self.0 = (self.0 & 0xffefffffffffffff) | ((value as u64) & 0x1) << 52; }

    /// Gets error vector 0Ch
    pub fn get_BSG_FV0C(&self) -> bool { (self.0 >> 52 & 0x1) != 0 }
        
    /// Sets error vector 0Bh

    pub fn set_BSG_FV0B(&mut self, value: bool){ self.0 = (self.0 & 0xfff7ffffffffffff) | ((value as u64) & 0x1) << 51; }

    /// Gets error vector 0Bh
    pub fn get_BSG_FV0B(&self) -> bool { (self.0 >> 51 & 0x1) != 0 }
        
    /// Sets error vector 0Ah

    pub fn set_BSG_FV0A(&mut self, value: bool){ self.0 = (self.0 & 0xfffbffffffffffff) | ((value as u64) & 0x1) << 50; }

    /// Gets error vector 0Ah
    pub fn get_BSG_FV0A(&self) -> bool { (self.0 >> 50 & 0x1) != 0 }
        
    /// Sets error vector 09h

    pub fn set_BSG_FV09(&mut self, value: bool){ self.0 = (self.0 & 0xfffdffffffffffff) | ((value as u64) & 0x1) << 49; }

    /// Gets error vector 09h
    pub fn get_BSG_FV09(&self) -> bool { (self.0 >> 49 & 0x1) != 0 }
        
    /// Sets error vector 08h

    pub fn set_BSG_FV08(&mut self, value: bool){ self.0 = (self.0 & 0xfffeffffffffffff) | ((value as u64) & 0x1) << 48; }

    /// Gets error vector 08h
    pub fn get_BSG_FV08(&self) -> bool { (self.0 >> 48 & 0x1) != 0 }
        
    /// Sets error vector 17h

    pub fn set_BSG_FV17(&mut self, value: bool){ self.0 = (self.0 & 0xffff7fffffffffff) | ((value as u64) & 0x1) << 47; }

    /// Gets error vector 17h
    pub fn get_BSG_FV17(&self) -> bool { (self.0 >> 47 & 0x1) != 0 }
        
    /// Sets error vector 16h

    pub fn set_BSG_FV16(&mut self, value: bool){ self.0 = (self.0 & 0xffffbfffffffffff) | ((value as u64) & 0x1) << 46; }

    /// Gets error vector 16h
    pub fn get_BSG_FV16(&self) -> bool { (self.0 >> 46 & 0x1) != 0 }
        
    /// Sets error vector 15h

    pub fn set_BSG_FV15(&mut self, value: bool){ self.0 = (self.0 & 0xffffdfffffffffff) | ((value as u64) & 0x1) << 45; }

    /// Gets error vector 15h
    pub fn get_BSG_FV15(&self) -> bool { (self.0 >> 45 & 0x1) != 0 }
        
    /// Sets error vector 14h

    pub fn set_BSG_FV14(&mut self, value: bool){ self.0 = (self.0 & 0xffffefffffffffff) | ((value as u64) & 0x1) << 44; }

    /// Gets error vector 14h
    pub fn get_BSG_FV14(&self) -> bool { (self.0 >> 44 & 0x1) != 0 }
        
    /// Sets error vector 13h

    pub fn set_BSG_FV13(&mut self, value: bool){ self.0 = (self.0 & 0xfffff7ffffffffff) | ((value as u64) & 0x1) << 43; }

    /// Gets error vector 13h
    pub fn get_BSG_FV13(&self) -> bool { (self.0 >> 43 & 0x1) != 0 }
        
    /// Sets error vector 12h

    pub fn set_BSG_FV12(&mut self, value: bool){ self.0 = (self.0 & 0xfffffbffffffffff) | ((value as u64) & 0x1) << 42; }

    /// Gets error vector 12h
    pub fn get_BSG_FV12(&self) -> bool { (self.0 >> 42 & 0x1) != 0 }
        
    /// Sets error vector 11h

    pub fn set_BSG_FV11(&mut self, value: bool){ self.0 = (self.0 & 0xfffffdffffffffff) | ((value as u64) & 0x1) << 41; }

    /// Gets error vector 11h
    pub fn get_BSG_FV11(&self) -> bool { (self.0 >> 41 & 0x1) != 0 }
        
    /// Sets error vector 10h

    pub fn set_BSG_FV10(&mut self, value: bool){ self.0 = (self.0 & 0xfffffeffffffffff) | ((value as u64) & 0x1) << 40; }

    /// Gets error vector 10h
    pub fn get_BSG_FV10(&self) -> bool { (self.0 >> 40 & 0x1) != 0 }
        
    /// Sets error vector 1Fh

    pub fn set_BSG_FV1F(&mut self, value: bool){ self.0 = (self.0 & 0xffffff7fffffffff) | ((value as u64) & 0x1) << 39; }

    /// Gets error vector 1Fh
    pub fn get_BSG_FV1F(&self) -> bool { (self.0 >> 39 & 0x1) != 0 }
        
    /// Sets error vector 1Eh

    pub fn set_BSG_FV1E(&mut self, value: bool){ self.0 = (self.0 & 0xffffffbfffffffff) | ((value as u64) & 0x1) << 38; }

    /// Gets error vector 1Eh
    pub fn get_BSG_FV1E(&self) -> bool { (self.0 >> 38 & 0x1) != 0 }
        
    /// Sets error vector 1Dh

    pub fn set_BSG_FV1D(&mut self, value: bool){ self.0 = (self.0 & 0xffffffdfffffffff) | ((value as u64) & 0x1) << 37; }

    /// Gets error vector 1Dh
    pub fn get_BSG_FV1D(&self) -> bool { (self.0 >> 37 & 0x1) != 0 }
        
    /// Sets Error vector 1Ch

    pub fn set_BSG_FV1C(&mut self, value: bool){ self.0 = (self.0 & 0xffffffefffffffff) | ((value as u64) & 0x1) << 36; }

    /// Gets Error vector 1Ch
    pub fn get_BSG_FV1C(&self) -> bool { (self.0 >> 36 & 0x1) != 0 }
        
    /// Sets error vector 1Bh

    pub fn set_BSG_FV1B(&mut self, value: bool){ self.0 = (self.0 & 0xfffffff7ffffffff) | ((value as u64) & 0x1) << 35; }

    /// Gets error vector 1Bh
    pub fn get_BSG_FV1B(&self) -> bool { (self.0 >> 35 & 0x1) != 0 }
        
    /// Sets Error vector 1Ah

    pub fn set_BSG_FV1A(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffbffffffff) | ((value as u64) & 0x1) << 34; }

    /// Gets Error vector 1Ah
    pub fn get_BSG_FV1A(&self) -> bool { (self.0 >> 34 & 0x1) != 0 }
        
    /// Sets error vector 19h

    pub fn set_BSG_FV19(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffdffffffff) | ((value as u64) & 0x1) << 33; }

    /// Gets error vector 19h
    pub fn get_BSG_FV19(&self) -> bool { (self.0 >> 33 & 0x1) != 0 }
        
    /// Sets error vector 18h

    pub fn set_BSG_FV18(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffeffffffff) | ((value as u64) & 0x1) << 32; }

    /// Gets error vector 18h
    pub fn get_BSG_FV18(&self) -> bool { (self.0 >> 32 & 0x1) != 0 }
        
    /// Sets state variable 08h

    pub fn set_BSG_PGV08(&mut self, value: bool){ self.0 = (self.0 & 0xffffffff7fffffff) | ((value as u64) & 0x1) << 31; }

    /// Gets state variable 08h
    pub fn get_BSG_PGV08(&self) -> bool { (self.0 >> 31 & 0x1) != 0 }
        
    /// Sets state variable 07h

    pub fn set_BSG_PGV07(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffbfffffff) | ((value as u64) & 0x1) << 30; }

    /// Gets state variable 07h
    pub fn get_BSG_PGV07(&self) -> bool { (self.0 >> 30 & 0x1) != 0 }
        
    /// Sets state variable 06h

    pub fn set_BSG_PGV06(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffdfffffff) | ((value as u64) & 0x1) << 29; }

    /// Gets state variable 06h
    pub fn get_BSG_PGV06(&self) -> bool { (self.0 >> 29 & 0x1) != 0 }
        
    /// Sets state variable 05h

    pub fn set_BSG_PGV05(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffefffffff) | ((value as u64) & 0x1) << 28; }

    /// Gets state variable 05h
    pub fn get_BSG_PGV05(&self) -> bool { (self.0 >> 28 & 0x1) != 0 }
        
    /// Sets state variable 04h

    pub fn set_BSG_PGV04(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffff7ffffff) | ((value as u64) & 0x1) << 27; }

    /// Gets state variable 04h
    pub fn get_BSG_PGV04(&self) -> bool { (self.0 >> 27 & 0x1) != 0 }
        
    /// Sets state variable 03h

    pub fn set_BSG_PGV03(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffbffffff) | ((value as u64) & 0x1) << 26; }

    /// Gets state variable 03h
    pub fn get_BSG_PGV03(&self) -> bool { (self.0 >> 26 & 0x1) != 0 }
        
    /// Sets state variable 02h

    pub fn set_BSG_PGV02(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffdffffff) | ((value as u64) & 0x1) << 25; }

    /// Gets state variable 02h
    pub fn get_BSG_PGV02(&self) -> bool { (self.0 >> 25 & 0x1) != 0 }
        
    /// Sets state variable 01h

    pub fn set_BSG_PGV01(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffeffffff) | ((value as u64) & 0x1) << 24; }

    /// Gets state variable 01h
    pub fn get_BSG_PGV01(&self) -> bool { (self.0 >> 24 & 0x1) != 0 }
        
}