
#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
/**
* AUTOGENERATED BY convert.py
* DO NOT EDIT THIS FILE!
*
* IF MODIFICATIONS NEED TO BE MADE, MODIFY can_data.txt!
*
* CAN Defintiion for ECU 'TVL'
*/
    
pub const TVL_A1_CAN_ID: u16 = 0x028C;
pub const TVL_A2_CAN_ID: u16 = 0x0044;
pub const TVL_A3_CAN_ID: u16 = 0x0018;
pub const SD_RS_TVL_CAN_ID: u16 = 0x07C8;


#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct TVL_A1(pub u64);

impl TVL_A1 {

	/// Gets CAN ID of TVL_A1
	pub const fn get_canid() -> u16 { TVL_A1_CAN_ID }
	pub fn new(data: u64) -> Self { Self(data) }
    /// Sets Front Left Seat - Togglebit

    pub fn set_SVL_TGL(&mut self, value: bool){ self.0 = (self.0 & 0x7fffffffffffffff) | ((value as u64) & 0x1) << 63; }

    /// Gets Front Left Seat - Togglebit
    pub fn get_SVL_TGL(&self) -> bool { (self.0 >> 63 & 0x1) != 0 }
        
    /// Sets Front Left Seat - Actuated

    pub fn set_SVL_SITZ_BET(&mut self, value: bool){ self.0 = (self.0 & 0xbfffffffffffffff) | ((value as u64) & 0x1) << 62; }

    /// Gets Front Left Seat - Actuated
    pub fn get_SVL_SITZ_BET(&self) -> bool { (self.0 >> 62 & 0x1) != 0 }
        
    /// Sets Front left seat - rear height down

    pub fn set_SVL_HI_AB(&mut self, value: bool){ self.0 = (self.0 & 0xf7ffffffffffffff) | ((value as u64) & 0x1) << 59; }

    /// Gets Front left seat - rear height down
    pub fn get_SVL_HI_AB(&self) -> bool { (self.0 >> 59 & 0x1) != 0 }
        
    /// Sets Front left seat - rear height up

    pub fn set_SVL_HI_AUF(&mut self, value: bool){ self.0 = (self.0 & 0xfbffffffffffffff) | ((value as u64) & 0x1) << 58; }

    /// Gets Front left seat - rear height up
    pub fn get_SVL_HI_AUF(&self) -> bool { (self.0 >> 58 & 0x1) != 0 }
        
    /// Sets Seat front left - lengthways back

    pub fn set_SVL_ZUR(&mut self, value: bool){ self.0 = (self.0 & 0xfdffffffffffffff) | ((value as u64) & 0x1) << 57; }

    /// Gets Seat front left - lengthways back
    pub fn get_SVL_ZUR(&self) -> bool { (self.0 >> 57 & 0x1) != 0 }
        
    /// Sets Seat in front on the left - longitudinally in front

    pub fn set_SVL_VOR(&mut self, value: bool){ self.0 = (self.0 & 0xfeffffffffffffff) | ((value as u64) & 0x1) << 56; }

    /// Gets Seat in front on the left - longitudinally in front
    pub fn get_SVL_VOR(&self) -> bool { (self.0 >> 56 & 0x1) != 0 }
        
    /// Sets Front left seat - headrest down

    pub fn set_SVL_KST_AB(&mut self, value: bool){ self.0 = (self.0 & 0xff7fffffffffffff) | ((value as u64) & 0x1) << 55; }

    /// Gets Front left seat - headrest down
    pub fn get_SVL_KST_AB(&self) -> bool { (self.0 >> 55 & 0x1) != 0 }
        
    /// Sets Front left seat - headrest up

    pub fn set_SVL_KST_AUF(&mut self, value: bool){ self.0 = (self.0 & 0xffbfffffffffffff) | ((value as u64) & 0x1) << 54; }

    /// Gets Front left seat - headrest up
    pub fn get_SVL_KST_AUF(&self) -> bool { (self.0 >> 54 & 0x1) != 0 }
        
    /// Sets Front left seat - front height down

    pub fn set_SVL_VO_AB(&mut self, value: bool){ self.0 = (self.0 & 0xffdfffffffffffff) | ((value as u64) & 0x1) << 53; }

    /// Gets Front left seat - front height down
    pub fn get_SVL_VO_AB(&self) -> bool { (self.0 >> 53 & 0x1) != 0 }
        
    /// Sets Seat front left - height front up

    pub fn set_SVL_VO_AUF(&mut self, value: bool){ self.0 = (self.0 & 0xffefffffffffffff) | ((value as u64) & 0x1) << 52; }

    /// Gets Seat front left - height front up
    pub fn get_SVL_VO_AUF(&self) -> bool { (self.0 >> 52 & 0x1) != 0 }
        
    /// Sets Front left seat - backrest

    pub fn set_SVL_LE_ZUR(&mut self, value: bool){ self.0 = (self.0 & 0xfff7ffffffffffff) | ((value as u64) & 0x1) << 51; }

    /// Gets Front left seat - backrest
    pub fn get_SVL_LE_ZUR(&self) -> bool { (self.0 >> 51 & 0x1) != 0 }
        
    /// Sets Front left seat - backrest forward

    pub fn set_SVL_LE_VOR(&mut self, value: bool){ self.0 = (self.0 & 0xfffbffffffffffff) | ((value as u64) & 0x1) << 50; }

    /// Gets Front left seat - backrest forward
    pub fn get_SVL_LE_VOR(&self) -> bool { (self.0 >> 50 & 0x1) != 0 }
        
    /// Sets Steering column backwards (towards the driver)

    pub fn set_LS_ZURUECK_LL(&mut self, value: bool){ self.0 = (self.0 & 0xffff7fffffffffff) | ((value as u64) & 0x1) << 47; }

    /// Gets Steering column backwards (towards the driver)
    pub fn get_LS_ZURUECK_LL(&self) -> bool { (self.0 >> 47 & 0x1) != 0 }
        
    /// Sets Steering column forward

    pub fn set_LS_VOR_LL(&mut self, value: bool){ self.0 = (self.0 & 0xffffbfffffffffff) | ((value as u64) & 0x1) << 46; }

    /// Gets Steering column forward
    pub fn get_LS_VOR_LL(&self) -> bool { (self.0 >> 46 & 0x1) != 0 }
        
    /// Sets Steering column down

    pub fn set_LS_AB_LL(&mut self, value: bool){ self.0 = (self.0 & 0xffffdfffffffffff) | ((value as u64) & 0x1) << 45; }

    /// Gets Steering column down
    pub fn get_LS_AB_LL(&self) -> bool { (self.0 >> 45 & 0x1) != 0 }
        
    /// Sets Steering column up

    pub fn set_LS_AUF_LL(&mut self, value: bool){ self.0 = (self.0 & 0xffffefffffffffff) | ((value as u64) & 0x1) << 44; }

    /// Gets Steering column up
    pub fn get_LS_AUF_LL(&self) -> bool { (self.0 >> 44 & 0x1) != 0 }
        
    /// Sets Memory front left - toggle bit

    pub fn set_MVL_TGL(&mut self, value: bool){ self.0 = (self.0 & 0xffffff7fffffffff) | ((value as u64) & 0x1) << 39; }

    /// Gets Memory front left - toggle bit
    pub fn get_MVL_TGL(&self) -> bool { (self.0 >> 39 & 0x1) != 0 }
        
    /// Sets Right exterior mirror Save button pressed

    pub fn set_SPI_RE_SP(&mut self, value: bool){ self.0 = (self.0 & 0xffffffbfffffffff) | ((value as u64) & 0x1) << 38; }

    /// Gets Right exterior mirror Save button pressed
    pub fn get_SPI_RE_SP(&self) -> bool { (self.0 >> 38 & 0x1) != 0 }
        
    /// Sets Memory front left - save position 3

    pub fn set_MVL_P3_SP(&mut self, value: bool){ self.0 = (self.0 & 0xffffffdfffffffff) | ((value as u64) & 0x1) << 37; }

    /// Gets Memory front left - save position 3
    pub fn get_MVL_P3_SP(&self) -> bool { (self.0 >> 37 & 0x1) != 0 }
        
    /// Sets Memory front left - save position 2

    pub fn set_MVL_P2_SP(&mut self, value: bool){ self.0 = (self.0 & 0xffffffefffffffff) | ((value as u64) & 0x1) << 36; }

    /// Gets Memory front left - save position 2
    pub fn get_MVL_P2_SP(&self) -> bool { (self.0 >> 36 & 0x1) != 0 }
        
    /// Sets Memory front left - save position 1

    pub fn set_MVL_P1_SP(&mut self, value: bool){ self.0 = (self.0 & 0xfffffff7ffffffff) | ((value as u64) & 0x1) << 35; }

    /// Gets Memory front left - save position 1
    pub fn get_MVL_P1_SP(&self) -> bool { (self.0 >> 35 & 0x1) != 0 }
        
    /// Sets Memory front left - take position 3

    pub fn set_MVL_P3_EN(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffbffffffff) | ((value as u64) & 0x1) << 34; }

    /// Gets Memory front left - take position 3
    pub fn get_MVL_P3_EN(&self) -> bool { (self.0 >> 34 & 0x1) != 0 }
        
    /// Sets Memory front left - take position 2

    pub fn set_MVL_P2_EN(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffdffffffff) | ((value as u64) & 0x1) << 33; }

    /// Gets Memory front left - take position 2
    pub fn get_MVL_P2_EN(&self) -> bool { (self.0 >> 33 & 0x1) != 0 }
        
    /// Sets Memory front left - take position 1

    pub fn set_MVL_P1_EN(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffeffffffff) | ((value as u64) & 0x1) << 32; }

    /// Gets Memory front left - take position 1
    pub fn get_MVL_P1_EN(&self) -> bool { (self.0 >> 32 & 0x1) != 0 }
        
    /// Sets Mirror adjustment switch operated

    pub fn set_SPVS_BET_LL(&mut self, value: bool){ self.0 = (self.0 & 0xffffffff7fffffff) | ((value as u64) & 0x1) << 31; }

    /// Gets Mirror adjustment switch operated
    pub fn get_SPVS_BET_LL(&self) -> bool { (self.0 >> 31 & 0x1) != 0 }
        
    /// Sets Outside mirror on the right after driving position

    pub fn set_SPI_RE_FAHREN(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffdfffffff) | ((value as u64) & 0x1) << 29; }

    /// Gets Outside mirror on the right after driving position
    pub fn get_SPI_RE_FAHREN(&self) -> bool { (self.0 >> 29 & 0x1) != 0 }
        
    /// Sets Outside mirror on the right after garage position

    pub fn set_SPI_RE_GARAGE(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffefffffff) | ((value as u64) & 0x1) << 28; }

    /// Gets Outside mirror on the right after garage position
    pub fn get_SPI_RE_GARAGE(&self) -> bool { (self.0 >> 28 & 0x1) != 0 }
        
    /// Sets Outside mirror right down

    pub fn set_SPI_RE_N_UN(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffff7ffffff) | ((value as u64) & 0x1) << 27; }

    /// Gets Outside mirror right down
    pub fn get_SPI_RE_N_UN(&self) -> bool { (self.0 >> 27 & 0x1) != 0 }
        
    /// Sets Outside mirror right up

    pub fn set_SPI_RE_N_OB(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffbffffff) | ((value as u64) & 0x1) << 26; }

    /// Gets Outside mirror right up
    pub fn get_SPI_RE_N_OB(&self) -> bool { (self.0 >> 26 & 0x1) != 0 }
        
    /// Sets Outside mirror right to right

    pub fn set_SPI_RE_N_RE(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffdffffff) | ((value as u64) & 0x1) << 25; }

    /// Gets Outside mirror right to right
    pub fn get_SPI_RE_N_RE(&self) -> bool { (self.0 >> 25 & 0x1) != 0 }
        
    /// Sets outside mirror right to left

    pub fn set_SPI_RE_N_LI(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffeffffff) | ((value as u64) & 0x1) << 24; }

    /// Gets outside mirror right to left
    pub fn get_SPI_RE_N_LI(&self) -> bool { (self.0 >> 24 & 0x1) != 0 }
        
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct TVL_A2(pub u64);

impl TVL_A2 {

	/// Gets CAN ID of TVL_A2
	pub const fn get_canid() -> u16 { TVL_A2_CAN_ID }
	pub fn new(data: u64) -> Self { Self(data) }
    /// Sets Open/close rear right window

    pub fn set_FHR_TVL(&mut self, value: bool){ self.0 = (self.0 & 0xff7fffffffffffff) | ((value as u64) & 0x1) << 55; }

    /// Gets Open/close rear right window
    pub fn get_FHR_TVL(&self) -> bool { (self.0 >> 55 & 0x1) != 0 }
        
    /// Sets Open/close rear left window

    pub fn set_FHL_TVL(&mut self, value: bool){ self.0 = (self.0 & 0xffbfffffffffffff) | ((value as u64) & 0x1) << 54; }

    /// Gets Open/close rear left window
    pub fn get_FHL_TVL(&self) -> bool { (self.0 >> 54 & 0x1) != 0 }
        
    /// Sets Open/close front right window

    pub fn set_FVR_TVL(&mut self, value: bool){ self.0 = (self.0 & 0xffdfffffffffffff) | ((value as u64) & 0x1) << 53; }

    /// Gets Open/close front right window
    pub fn get_FVR_TVL(&self) -> bool { (self.0 >> 53 & 0x1) != 0 }
        
    /// Sets Open/close front left window

    pub fn set_FVL_TVL(&mut self, value: bool){ self.0 = (self.0 & 0xffefffffffffffff) | ((value as u64) & 0x1) << 52; }

    /// Gets Open/close front left window
    pub fn get_FVL_TVL(&self) -> bool { (self.0 >> 52 & 0x1) != 0 }
        
    /// Sets Open/close SHD/top

    pub fn set_SHD_TVL(&mut self, value: bool){ self.0 = (self.0 & 0xfff7ffffffffffff) | ((value as u64) & 0x1) << 51; }

    /// Gets Open/close SHD/top
    pub fn get_SHD_TVL(&self) -> bool { (self.0 >> 51 & 0x1) != 0 }
        
    /// Sets direction comfort operation: open [0], close [1]

    pub fn set_KB_RI_TVL(&mut self, value: bool){ self.0 = (self.0 & 0xfffbffffffffffff) | ((value as u64) & 0x1) << 50; }

    /// Gets direction comfort operation: open [0], close [1]
    pub fn get_KB_RI_TVL(&self) -> bool { (self.0 >> 50 & 0x1) != 0 }
        
    /// Sets Comfort control Automatic operation [1] Manual [0]

    pub fn set_KB_MOD_TVL(&mut self, value: bool){ self.0 = (self.0 & 0xfffdffffffffffff) | ((value as u64) & 0x1) << 49; }

    /// Gets Comfort control Automatic operation [1] Manual [0]
    pub fn get_KB_MOD_TVL(&self) -> bool { (self.0 >> 49 & 0x1) != 0 }
        
    /// Sets Rear right window - close automatically

    pub fn set_FHR_AS_LL(&mut self, value: bool){ self.0 = (self.0 & 0xffff7fffffffffff) | ((value as u64) & 0x1) << 47; }

    /// Gets Rear right window - close automatically
    pub fn get_FHR_AS_LL(&self) -> bool { (self.0 >> 47 & 0x1) != 0 }
        
    /// Sets Rear right window - close manually

    pub fn set_FHR_MS_LL(&mut self, value: bool){ self.0 = (self.0 & 0xffffbfffffffffff) | ((value as u64) & 0x1) << 46; }

    /// Gets Rear right window - close manually
    pub fn get_FHR_MS_LL(&self) -> bool { (self.0 >> 46 & 0x1) != 0 }
        
    /// Sets Rear right window - open manually

    pub fn set_FHR_MOE_LL(&mut self, value: bool){ self.0 = (self.0 & 0xffffdfffffffffff) | ((value as u64) & 0x1) << 45; }

    /// Gets Rear right window - open manually
    pub fn get_FHR_MOE_LL(&self) -> bool { (self.0 >> 45 & 0x1) != 0 }
        
    /// Sets Rear right window - open automatically

    pub fn set_FHR_AOE_LL(&mut self, value: bool){ self.0 = (self.0 & 0xffffefffffffffff) | ((value as u64) & 0x1) << 44; }

    /// Gets Rear right window - open automatically
    pub fn get_FHR_AOE_LL(&self) -> bool { (self.0 >> 44 & 0x1) != 0 }
        
    /// Sets Rear left window - close automatically

    pub fn set_FHL_AS_LL(&mut self, value: bool){ self.0 = (self.0 & 0xfffff7ffffffffff) | ((value as u64) & 0x1) << 43; }

    /// Gets Rear left window - close automatically
    pub fn get_FHL_AS_LL(&self) -> bool { (self.0 >> 43 & 0x1) != 0 }
        
    /// Sets Rear left window - close manually

    pub fn set_FHL_MS_LL(&mut self, value: bool){ self.0 = (self.0 & 0xfffffbffffffffff) | ((value as u64) & 0x1) << 42; }

    /// Gets Rear left window - close manually
    pub fn get_FHL_MS_LL(&self) -> bool { (self.0 >> 42 & 0x1) != 0 }
        
    /// Sets Rear left window - open manually

    pub fn set_FHL_MOE_LL(&mut self, value: bool){ self.0 = (self.0 & 0xfffffdffffffffff) | ((value as u64) & 0x1) << 41; }

    /// Gets Rear left window - open manually
    pub fn get_FHL_MOE_LL(&self) -> bool { (self.0 >> 41 & 0x1) != 0 }
        
    /// Sets Rear left window - open automatically

    pub fn set_FHL_AOE_LL(&mut self, value: bool){ self.0 = (self.0 & 0xfffffeffffffffff) | ((value as u64) & 0x1) << 40; }

    /// Gets Rear left window - open automatically
    pub fn get_FHL_AOE_LL(&self) -> bool { (self.0 >> 40 & 0x1) != 0 }
        
    /// Sets Front right window - close automatically

    pub fn set_FVR_AS(&mut self, value: bool){ self.0 = (self.0 & 0xffffff7fffffffff) | ((value as u64) & 0x1) << 39; }

    /// Gets Front right window - close automatically
    pub fn get_FVR_AS(&self) -> bool { (self.0 >> 39 & 0x1) != 0 }
        
    /// Sets Front right window - close manually

    pub fn set_FVR_MS(&mut self, value: bool){ self.0 = (self.0 & 0xffffffbfffffffff) | ((value as u64) & 0x1) << 38; }

    /// Gets Front right window - close manually
    pub fn get_FVR_MS(&self) -> bool { (self.0 >> 38 & 0x1) != 0 }
        
    /// Sets Front right window - open manually

    pub fn set_FVR_MOE(&mut self, value: bool){ self.0 = (self.0 & 0xffffffdfffffffff) | ((value as u64) & 0x1) << 37; }

    /// Gets Front right window - open manually
    pub fn get_FVR_MOE(&self) -> bool { (self.0 >> 37 & 0x1) != 0 }
        
    /// Sets Front right window - open automatically

    pub fn set_FVR_AOE(&mut self, value: bool){ self.0 = (self.0 & 0xffffffefffffffff) | ((value as u64) & 0x1) << 36; }

    /// Gets Front right window - open automatically
    pub fn get_FVR_AOE(&self) -> bool { (self.0 >> 36 & 0x1) != 0 }
        
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct TVL_A3(pub u64);

impl TVL_A3 {

	/// Gets CAN ID of TVL_A3
	pub const fn get_canid() -> u16 { TVL_A3_CAN_ID }
	pub fn new(data: u64) -> Self { Self(data) }
    /// Sets Mirror adjustment switch in the right position

    pub fn set_SPVS_BF_LL(&mut self, value: bool){ self.0 = (self.0 & 0x7fffffffffffffff) | ((value as u64) & 0x1) << 63; }

    /// Gets Mirror adjustment switch in the right position
    pub fn get_SPVS_BF_LL(&self) -> bool { (self.0 >> 63 & 0x1) != 0 }
        
    /// Sets Trunk lid remote release

    pub fn set_HFE_LL(&mut self, value: bool){ self.0 = (self.0 & 0xbfffffffffffffff) | ((value as u64) & 0x1) << 62; }

    /// Gets Trunk lid remote release
    pub fn get_HFE_LL(&self) -> bool { (self.0 >> 62 & 0x1) != 0 }
        
    /// Sets Child lock on

    pub fn set_KISI_EIN_LL(&mut self, value: bool){ self.0 = (self.0 & 0xdfffffffffffffff) | ((value as u64) & 0x1) << 61; }

    /// Gets Child lock on
    pub fn get_KISI_EIN_LL(&self) -> bool { (self.0 >> 61 & 0x1) != 0 }
        
    /// Sets Additional indicator on the left defective

    pub fn set_ZBLL_DEF(&mut self, value: bool){ self.0 = (self.0 & 0xefffffffffffffff) | ((value as u64) & 0x1) << 60; }

    /// Gets Additional indicator on the left defective
    pub fn get_ZBLL_DEF(&self) -> bool { (self.0 >> 60 & 0x1) != 0 }
        
    /// Sets Trunk lid remote closure

    pub fn set_HFS_LL(&mut self, value: bool){ self.0 = (self.0 & 0xf7ffffffffffffff) | ((value as u64) & 0x1) << 59; }

    /// Gets Trunk lid remote closure
    pub fn get_HFS_LL(&self) -> bool { (self.0 >> 59 & 0x1) != 0 }
        
    /// Sets Front left window normalized

    pub fn set_FVL_NORM(&mut self, value: bool){ self.0 = (self.0 & 0xff7fffffffffffff) | ((value as u64) & 0x1) << 55; }

    /// Gets Front left window normalized
    pub fn get_FVL_NORM(&self) -> bool { (self.0 >> 55 & 0x1) != 0 }
        
    /// Sets Front left window blocked

    pub fn set_FVL_BLOCK(&mut self, value: bool){ self.0 = (self.0 & 0xffbfffffffffffff) | ((value as u64) & 0x1) << 54; }

    /// Gets Front left window blocked
    pub fn get_FVL_BLOCK(&self) -> bool { (self.0 >> 54 & 0x1) != 0 }
        
    /// Sets Front left window position. Conversion formula (To raw from real): y=(x+512.0)/0.25 (Unit: 1/Ankerumdre)

    pub fn set_FESTE_VL(&mut self, value: u16){ self.0 = (self.0 & 0xfff000ffffffffff) | ((value as u64) & 0xfff) << 40; }

    /// Gets Front left window position. Conversion formula (To real from raw): y=(0.25x)-512.0 (Unit: 1/Ankerumdre)
    pub fn get_FESTE_VL(&self) -> u16 { (self.0 >> 40 & 0xfff) as u16 }
        
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct SD_RS_TVL(pub u64);

impl SD_RS_TVL {

	/// Gets CAN ID of SD_RS_TVL
	pub const fn get_canid() -> u16 { SD_RS_TVL_CAN_ID }
	pub fn new(data: u64) -> Self { Self(data) }
    /// Sets Identification for > 8 bytes

    pub fn set_TVL_KENN(&mut self, value: bool){ self.0 = (self.0 & 0x7fffffffffffffff) | ((value as u64) & 0x1) << 63; }

    /// Gets Identification for > 8 bytes
    pub fn get_TVL_KENN(&self) -> bool { (self.0 >> 63 & 0x1) != 0 }
        
    /// Sets error vector 07h

    pub fn set_TVL_FV07(&mut self, value: bool){ self.0 = (self.0 & 0xbfffffffffffffff) | ((value as u64) & 0x1) << 62; }

    /// Gets error vector 07h
    pub fn get_TVL_FV07(&self) -> bool { (self.0 >> 62 & 0x1) != 0 }
        
    /// Sets error vector 06h

    pub fn set_TVL_FV06(&mut self, value: bool){ self.0 = (self.0 & 0xdfffffffffffffff) | ((value as u64) & 0x1) << 61; }

    /// Gets error vector 06h
    pub fn get_TVL_FV06(&self) -> bool { (self.0 >> 61 & 0x1) != 0 }
        
    /// Sets error vector 05h

    pub fn set_TVL_FV05(&mut self, value: bool){ self.0 = (self.0 & 0xefffffffffffffff) | ((value as u64) & 0x1) << 60; }

    /// Gets error vector 05h
    pub fn get_TVL_FV05(&self) -> bool { (self.0 >> 60 & 0x1) != 0 }
        
    /// Sets error vector 04h

    pub fn set_TVL_FV04(&mut self, value: bool){ self.0 = (self.0 & 0xf7ffffffffffffff) | ((value as u64) & 0x1) << 59; }

    /// Gets error vector 04h
    pub fn get_TVL_FV04(&self) -> bool { (self.0 >> 59 & 0x1) != 0 }
        
    /// Sets error vector 03h

    pub fn set_TVL_FV03(&mut self, value: bool){ self.0 = (self.0 & 0xfbffffffffffffff) | ((value as u64) & 0x1) << 58; }

    /// Gets error vector 03h
    pub fn get_TVL_FV03(&self) -> bool { (self.0 >> 58 & 0x1) != 0 }
        
    /// Sets error vector 02h

    pub fn set_TVL_FV02(&mut self, value: bool){ self.0 = (self.0 & 0xfdffffffffffffff) | ((value as u64) & 0x1) << 57; }

    /// Gets error vector 02h
    pub fn get_TVL_FV02(&self) -> bool { (self.0 >> 57 & 0x1) != 0 }
        
    /// Sets error vector 01h

    pub fn set_TVL_FV01(&mut self, value: bool){ self.0 = (self.0 & 0xfeffffffffffffff) | ((value as u64) & 0x1) << 56; }

    /// Gets error vector 01h
    pub fn get_TVL_FV01(&self) -> bool { (self.0 >> 56 & 0x1) != 0 }
        
    /// Sets error vector 0Fh

    pub fn set_TVL_FV0F(&mut self, value: bool){ self.0 = (self.0 & 0xff7fffffffffffff) | ((value as u64) & 0x1) << 55; }

    /// Gets error vector 0Fh
    pub fn get_TVL_FV0F(&self) -> bool { (self.0 >> 55 & 0x1) != 0 }
        
    /// Sets error vector 0Eh

    pub fn set_TVL_FV0E(&mut self, value: bool){ self.0 = (self.0 & 0xffbfffffffffffff) | ((value as u64) & 0x1) << 54; }

    /// Gets error vector 0Eh
    pub fn get_TVL_FV0E(&self) -> bool { (self.0 >> 54 & 0x1) != 0 }
        
    /// Sets error vector 0Dh

    pub fn set_TVL_FV0D(&mut self, value: bool){ self.0 = (self.0 & 0xffdfffffffffffff) | ((value as u64) & 0x1) << 53; }

    /// Gets error vector 0Dh
    pub fn get_TVL_FV0D(&self) -> bool { (self.0 >> 53 & 0x1) != 0 }
        
    /// Sets error vector 0Ch

    pub fn set_TVL_FV0C(&mut self, value: bool){ self.0 = (self.0 & 0xffefffffffffffff) | ((value as u64) & 0x1) << 52; }

    /// Gets error vector 0Ch
    pub fn get_TVL_FV0C(&self) -> bool { (self.0 >> 52 & 0x1) != 0 }
        
    /// Sets error vector 0Bh

    pub fn set_TVL_FV0B(&mut self, value: bool){ self.0 = (self.0 & 0xfff7ffffffffffff) | ((value as u64) & 0x1) << 51; }

    /// Gets error vector 0Bh
    pub fn get_TVL_FV0B(&self) -> bool { (self.0 >> 51 & 0x1) != 0 }
        
    /// Sets error vector 0Ah

    pub fn set_TVL_FV0A(&mut self, value: bool){ self.0 = (self.0 & 0xfffbffffffffffff) | ((value as u64) & 0x1) << 50; }

    /// Gets error vector 0Ah
    pub fn get_TVL_FV0A(&self) -> bool { (self.0 >> 50 & 0x1) != 0 }
        
    /// Sets error vector 09h

    pub fn set_TVL_FV09(&mut self, value: bool){ self.0 = (self.0 & 0xfffdffffffffffff) | ((value as u64) & 0x1) << 49; }

    /// Gets error vector 09h
    pub fn get_TVL_FV09(&self) -> bool { (self.0 >> 49 & 0x1) != 0 }
        
    /// Sets error vector 08h

    pub fn set_TVL_FV08(&mut self, value: bool){ self.0 = (self.0 & 0xfffeffffffffffff) | ((value as u64) & 0x1) << 48; }

    /// Gets error vector 08h
    pub fn get_TVL_FV08(&self) -> bool { (self.0 >> 48 & 0x1) != 0 }
        
    /// Sets error vector 17h

    pub fn set_TVL_FV17(&mut self, value: bool){ self.0 = (self.0 & 0xffff7fffffffffff) | ((value as u64) & 0x1) << 47; }

    /// Gets error vector 17h
    pub fn get_TVL_FV17(&self) -> bool { (self.0 >> 47 & 0x1) != 0 }
        
    /// Sets error vector 16h

    pub fn set_TVL_FV16(&mut self, value: bool){ self.0 = (self.0 & 0xffffbfffffffffff) | ((value as u64) & 0x1) << 46; }

    /// Gets error vector 16h
    pub fn get_TVL_FV16(&self) -> bool { (self.0 >> 46 & 0x1) != 0 }
        
    /// Sets error vector 15h

    pub fn set_TVL_FV15(&mut self, value: bool){ self.0 = (self.0 & 0xffffdfffffffffff) | ((value as u64) & 0x1) << 45; }

    /// Gets error vector 15h
    pub fn get_TVL_FV15(&self) -> bool { (self.0 >> 45 & 0x1) != 0 }
        
    /// Sets error vector 14h

    pub fn set_TVL_FV14(&mut self, value: bool){ self.0 = (self.0 & 0xffffefffffffffff) | ((value as u64) & 0x1) << 44; }

    /// Gets error vector 14h
    pub fn get_TVL_FV14(&self) -> bool { (self.0 >> 44 & 0x1) != 0 }
        
    /// Sets error vector 13h

    pub fn set_TVL_FV13(&mut self, value: bool){ self.0 = (self.0 & 0xfffff7ffffffffff) | ((value as u64) & 0x1) << 43; }

    /// Gets error vector 13h
    pub fn get_TVL_FV13(&self) -> bool { (self.0 >> 43 & 0x1) != 0 }
        
    /// Sets error vector 12h

    pub fn set_TVL_FV12(&mut self, value: bool){ self.0 = (self.0 & 0xfffffbffffffffff) | ((value as u64) & 0x1) << 42; }

    /// Gets error vector 12h
    pub fn get_TVL_FV12(&self) -> bool { (self.0 >> 42 & 0x1) != 0 }
        
    /// Sets error vector 11h

    pub fn set_TVL_FV11(&mut self, value: bool){ self.0 = (self.0 & 0xfffffdffffffffff) | ((value as u64) & 0x1) << 41; }

    /// Gets error vector 11h
    pub fn get_TVL_FV11(&self) -> bool { (self.0 >> 41 & 0x1) != 0 }
        
    /// Sets error vector 10h

    pub fn set_TVL_FV10(&mut self, value: bool){ self.0 = (self.0 & 0xfffffeffffffffff) | ((value as u64) & 0x1) << 40; }

    /// Gets error vector 10h
    pub fn get_TVL_FV10(&self) -> bool { (self.0 >> 40 & 0x1) != 0 }
        
    /// Sets error vector 1Fh

    pub fn set_TVL_FV1F(&mut self, value: bool){ self.0 = (self.0 & 0xffffff7fffffffff) | ((value as u64) & 0x1) << 39; }

    /// Gets error vector 1Fh
    pub fn get_TVL_FV1F(&self) -> bool { (self.0 >> 39 & 0x1) != 0 }
        
    /// Sets error vector 1Eh

    pub fn set_TVL_FV1E(&mut self, value: bool){ self.0 = (self.0 & 0xffffffbfffffffff) | ((value as u64) & 0x1) << 38; }

    /// Gets error vector 1Eh
    pub fn get_TVL_FV1E(&self) -> bool { (self.0 >> 38 & 0x1) != 0 }
        
    /// Sets error vector 1Dh

    pub fn set_TVL_FV1D(&mut self, value: bool){ self.0 = (self.0 & 0xffffffdfffffffff) | ((value as u64) & 0x1) << 37; }

    /// Gets error vector 1Dh
    pub fn get_TVL_FV1D(&self) -> bool { (self.0 >> 37 & 0x1) != 0 }
        
    /// Sets Error vector 1Ch

    pub fn set_TVL_FV1C(&mut self, value: bool){ self.0 = (self.0 & 0xffffffefffffffff) | ((value as u64) & 0x1) << 36; }

    /// Gets Error vector 1Ch
    pub fn get_TVL_FV1C(&self) -> bool { (self.0 >> 36 & 0x1) != 0 }
        
    /// Sets error vector 1Bh

    pub fn set_TVL_FV1B(&mut self, value: bool){ self.0 = (self.0 & 0xfffffff7ffffffff) | ((value as u64) & 0x1) << 35; }

    /// Gets error vector 1Bh
    pub fn get_TVL_FV1B(&self) -> bool { (self.0 >> 35 & 0x1) != 0 }
        
    /// Sets Error vector 1Ah

    pub fn set_TVL_FV1A(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffbffffffff) | ((value as u64) & 0x1) << 34; }

    /// Gets Error vector 1Ah
    pub fn get_TVL_FV1A(&self) -> bool { (self.0 >> 34 & 0x1) != 0 }
        
    /// Sets error vector 19h

    pub fn set_TVL_FV19(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffdffffffff) | ((value as u64) & 0x1) << 33; }

    /// Gets error vector 19h
    pub fn get_TVL_FV19(&self) -> bool { (self.0 >> 33 & 0x1) != 0 }
        
    /// Sets error vector 18h

    pub fn set_TVL_FV18(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffeffffffff) | ((value as u64) & 0x1) << 32; }

    /// Gets error vector 18h
    pub fn get_TVL_FV18(&self) -> bool { (self.0 >> 32 & 0x1) != 0 }
        
    /// Sets error vector 27h

    pub fn set_TVL_FV27(&mut self, value: bool){ self.0 = (self.0 & 0xffffffff7fffffff) | ((value as u64) & 0x1) << 31; }

    /// Gets error vector 27h
    pub fn get_TVL_FV27(&self) -> bool { (self.0 >> 31 & 0x1) != 0 }
        
    /// Sets error vector 26h

    pub fn set_TVL_FV26(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffbfffffff) | ((value as u64) & 0x1) << 30; }

    /// Gets error vector 26h
    pub fn get_TVL_FV26(&self) -> bool { (self.0 >> 30 & 0x1) != 0 }
        
    /// Sets error vector 25h

    pub fn set_TVL_FV25(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffdfffffff) | ((value as u64) & 0x1) << 29; }

    /// Gets error vector 25h
    pub fn get_TVL_FV25(&self) -> bool { (self.0 >> 29 & 0x1) != 0 }
        
    /// Sets error vector 24h

    pub fn set_TVL_FV24(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffefffffff) | ((value as u64) & 0x1) << 28; }

    /// Gets error vector 24h
    pub fn get_TVL_FV24(&self) -> bool { (self.0 >> 28 & 0x1) != 0 }
        
    /// Sets error vector 23h

    pub fn set_TVL_FV23(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffff7ffffff) | ((value as u64) & 0x1) << 27; }

    /// Gets error vector 23h
    pub fn get_TVL_FV23(&self) -> bool { (self.0 >> 27 & 0x1) != 0 }
        
    /// Sets error vector 22h

    pub fn set_TVL_FV22(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffbffffff) | ((value as u64) & 0x1) << 26; }

    /// Gets error vector 22h
    pub fn get_TVL_FV22(&self) -> bool { (self.0 >> 26 & 0x1) != 0 }
        
    /// Sets error vector 21h

    pub fn set_TVL_FV21(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffdffffff) | ((value as u64) & 0x1) << 25; }

    /// Gets error vector 21h
    pub fn get_TVL_FV21(&self) -> bool { (self.0 >> 25 & 0x1) != 0 }
        
    /// Sets error vector 20h

    pub fn set_TVL_FV20(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffeffffff) | ((value as u64) & 0x1) << 24; }

    /// Gets error vector 20h
    pub fn get_TVL_FV20(&self) -> bool { (self.0 >> 24 & 0x1) != 0 }
        
    /// Sets error vector 2Fh

    pub fn set_TVL_FV2F(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffff7fffff) | ((value as u64) & 0x1) << 23; }

    /// Gets error vector 2Fh
    pub fn get_TVL_FV2F(&self) -> bool { (self.0 >> 23 & 0x1) != 0 }
        
    /// Sets error vector 2Eh

    pub fn set_TVL_FV2E(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffffbfffff) | ((value as u64) & 0x1) << 22; }

    /// Gets error vector 2Eh
    pub fn get_TVL_FV2E(&self) -> bool { (self.0 >> 22 & 0x1) != 0 }
        
    /// Sets error vector 2Dh

    pub fn set_TVL_FV2D(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffffdfffff) | ((value as u64) & 0x1) << 21; }

    /// Gets error vector 2Dh
    pub fn get_TVL_FV2D(&self) -> bool { (self.0 >> 21 & 0x1) != 0 }
        
    /// Sets error vector 2Ch

    pub fn set_TVL_FV2C(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffffefffff) | ((value as u64) & 0x1) << 20; }

    /// Gets error vector 2Ch
    pub fn get_TVL_FV2C(&self) -> bool { (self.0 >> 20 & 0x1) != 0 }
        
    /// Sets error vector 2Bh

    pub fn set_TVL_FV2B(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffff7ffff) | ((value as u64) & 0x1) << 19; }

    /// Gets error vector 2Bh
    pub fn get_TVL_FV2B(&self) -> bool { (self.0 >> 19 & 0x1) != 0 }
        
    /// Sets Error vector 2Ah

    pub fn set_TVL_FV2A(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffffbffff) | ((value as u64) & 0x1) << 18; }

    /// Gets Error vector 2Ah
    pub fn get_TVL_FV2A(&self) -> bool { (self.0 >> 18 & 0x1) != 0 }
        
    /// Sets error vector 29h

    pub fn set_TVL_FV29(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffffdffff) | ((value as u64) & 0x1) << 17; }

    /// Gets error vector 29h
    pub fn get_TVL_FV29(&self) -> bool { (self.0 >> 17 & 0x1) != 0 }
        
    /// Sets error vector 28h

    pub fn set_TVL_FV28(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffffeffff) | ((value as u64) & 0x1) << 16; }

    /// Gets error vector 28h
    pub fn get_TVL_FV28(&self) -> bool { (self.0 >> 16 & 0x1) != 0 }
        
    /// Sets error vector 37h

    pub fn set_TVL_FV37(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffffff7fff) | ((value as u64) & 0x1) << 15; }

    /// Gets error vector 37h
    pub fn get_TVL_FV37(&self) -> bool { (self.0 >> 15 & 0x1) != 0 }
        
    /// Sets error vector 36h

    pub fn set_TVL_FV36(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffffffbfff) | ((value as u64) & 0x1) << 14; }

    /// Gets error vector 36h
    pub fn get_TVL_FV36(&self) -> bool { (self.0 >> 14 & 0x1) != 0 }
        
    /// Sets error vector 35h

    pub fn set_TVL_FV35(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffffffdfff) | ((value as u64) & 0x1) << 13; }

    /// Gets error vector 35h
    pub fn get_TVL_FV35(&self) -> bool { (self.0 >> 13 & 0x1) != 0 }
        
    /// Sets error vector 34h

    pub fn set_TVL_FV34(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffffffefff) | ((value as u64) & 0x1) << 12; }

    /// Gets error vector 34h
    pub fn get_TVL_FV34(&self) -> bool { (self.0 >> 12 & 0x1) != 0 }
        
    /// Sets error vector 33h

    pub fn set_TVL_FV33(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffffff7ff) | ((value as u64) & 0x1) << 11; }

    /// Gets error vector 33h
    pub fn get_TVL_FV33(&self) -> bool { (self.0 >> 11 & 0x1) != 0 }
        
    /// Sets error vector 32h

    pub fn set_TVL_FV32(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffffffbff) | ((value as u64) & 0x1) << 10; }

    /// Gets error vector 32h
    pub fn get_TVL_FV32(&self) -> bool { (self.0 >> 10 & 0x1) != 0 }
        
    /// Sets error vector 31h

    pub fn set_TVL_FV31(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffffffdff) | ((value as u64) & 0x1) << 9; }

    /// Gets error vector 31h
    pub fn get_TVL_FV31(&self) -> bool { (self.0 >> 9 & 0x1) != 0 }
        
    /// Sets error vector 30h

    pub fn set_TVL_FV30(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffffffeff) | ((value as u64) & 0x1) << 8; }

    /// Gets error vector 30h
    pub fn get_TVL_FV30(&self) -> bool { (self.0 >> 8 & 0x1) != 0 }
        
    /// Sets state variable 04h

    pub fn set_TVL_PGV04(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffffffff7f) | ((value as u64) & 0x1) << 7; }

    /// Gets state variable 04h
    pub fn get_TVL_PGV04(&self) -> bool { (self.0 >> 7 & 0x1) != 0 }
        
    /// Sets state variable 03h

    pub fn set_TVL_PGV03(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffffffffbf) | ((value as u64) & 0x1) << 6; }

    /// Gets state variable 03h
    pub fn get_TVL_PGV03(&self) -> bool { (self.0 >> 6 & 0x1) != 0 }
        
    /// Sets state variable 02h

    pub fn set_TVL_PGV02(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffffffffdf) | ((value as u64) & 0x1) << 5; }

    /// Gets state variable 02h
    pub fn get_TVL_PGV02(&self) -> bool { (self.0 >> 5 & 0x1) != 0 }
        
    /// Sets state variable 01h

    pub fn set_TVL_PGV01(&mut self, value: bool){ self.0 = (self.0 & 0xffffffffffffffef) | ((value as u64) & 0x1) << 4; }

    /// Gets state variable 01h
    pub fn get_TVL_PGV01(&self) -> bool { (self.0 >> 4 & 0x1) != 0 }
        
    /// Sets error vector 3Bh

    pub fn set_TVL_FV3B(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffffffff7) | ((value as u64) & 0x1) << 3; }

    /// Gets error vector 3Bh
    pub fn get_TVL_FV3B(&self) -> bool { (self.0 >> 3 & 0x1) != 0 }
        
    /// Sets Error vector 3Ah

    pub fn set_TVL_FV3A(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffffffffb) | ((value as u64) & 0x1) << 2; }

    /// Gets Error vector 3Ah
    pub fn get_TVL_FV3A(&self) -> bool { (self.0 >> 2 & 0x1) != 0 }
        
    /// Sets error vector 39h

    pub fn set_TVL_FV39(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffffffffd) | ((value as u64) & 0x1) << 1; }

    /// Gets error vector 39h
    pub fn get_TVL_FV39(&self) -> bool { (self.0 >> 1 & 0x1) != 0 }
        
    /// Sets error vector 38h

    pub fn set_TVL_FV38(&mut self, value: bool){ self.0 = (self.0 & 0xfffffffffffffffe) | ((value as u64) & 0x1) << 0; }

    /// Gets error vector 38h
    pub fn get_TVL_FV38(&self) -> bool { (self.0 >> 0 & 0x1) != 0 }
        
}