[package]
name = "w211_can"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socketcan = "2.0.0"
socketcan-isotp = "1.0.1"
